Import relevant libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression

Load the data

In [2]:
data = pd.read_csv('1.01.+Simple+linear+regression.csv')

In [3]:
data.head()

SAT   GPA
0  1714  2.40
1  1664  2.52
2  1760  2.54
3  1685  2.74
4  1693  2.83

Create regression

In [4]:
x= data['SAT']
y = data['GPA']

In [5]:
x.shape


(84,)

In [6]:
y.shape

(84,)

In [11]:
x_matrix = x.values.reshape(-1,1)
x_matrix.shape

(84, 1)

Regression itself

In [13]:
reg = LinearRegression()

In [14]:
reg.fit(x_matrix,y)

LinearRegression()

In [15]:
reg.get_params()

{'copy_X': True,
 'fit_intercept': True,
 'n_jobs': None,
 'normalize': False,
 'positive': False}

R-squared

In [16]:
reg.score(x_matrix,y)

0.40600391479679765

Coefficient

In [17]:
reg.coef_

array([0.00165569])

Intercept

In [18]:
reg.intercept_

0.2750402996602803

Making predictions

In [20]:
x_pred = pd.DataFrame(data=[1740]).values.reshape(-1,1)

reg.predict(x_pred)

array([3.15593751])

In [21]:
new_data = pd.DataFrame(data=[1740,1767],columns=['SAT'])

In [23]:
reg.predict(new_data)

array([3.15593751, 3.20064108])

In [24]:
new_data['Predicted GPA'] = reg.predict(new_data)

In [25]:
new_data

SAT  Predicted GPA
0  1740       3.155938
1  1767       3.200641